### ISSUE TITLE
Sharing at user level

### ISSUE THREAD

**Issue by giannik** [EtchUK/Etch.OrchardCore.ContentPermissions#1]
Firstly, great module, very usefull.
Do you think this can be extended to set permissions at user level ?
Example, I wish to share a content item to a system  user (granting readonly, or edit permissions) ,similar to google docs which allows you to share a document to a user by his email.
Thanks again.

**Comment by peterkeating** [comment]
Good idea!

**Comment by vitalybrandes** [comment]
Agree and even more, Sharing to roles will be fantastic as well!

**Comment by peterkeating** [comment]
@vitalybrandes This module already supports sharing at a role level 👍

**Comment by abbasl7** [comment]
Thanks for the great module, @peterkeating 
Is this enhancement being developed or considered for next release?

**Comment by peterkeating** [comment]
@abbasl7 I need to upgrade the module to the latest version of Orchard Core, when I do that I'll see if I can resolve this issue.
