### ISSUE TITLE
Question: Can this module also be used to set content item level permissions by code?

### ISSUE THREAD

**Issue by TheShihan** [EtchUK/Etch.OrchardCore.ContentPermissions#7]
Can this module also be used to set content item level permissions by code? Or is this something that would still be needed to be done manually by an administrator?
Or maybe setting item level permissions by code is possible regardless of this module but this module will make sure that such permissions work on the content items?

**Comment by peterkeating** [comment]
What kind of code are you thinking of writing? If you're writing code then it's likely you're creating a custom module that wouldn't require a dependency on this module. This module enables you to do it without requiring code and can be controlled by administrators within the CMS. By all means use the same code that we're using the validate whether a user has permission to access a content item though - https://github.com/EtchUK/Etch.OrchardCore.ContentPermissions/blob/master/Services/ContentPermissionsService.cs#L36
